//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_WPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coexecutors
    {
        public int id_coexecutors { get; set; }
        public Nullable<int> id_users { get; set; }
        public Nullable<int> id_program { get; set; }
    
        public virtual Programs Programs { get; set; }
        public virtual Users Users { get; set; }
    }
}
